### ISSUE TITLE
What is the speed of detection ？

### ISSUE THREAD

**Issue by tzhang2014** [EricZgw/PyramidBox#1]
for 640*480，What is the speed of detection？ GPU memory and CPU memory? Thx

**Comment by EricZgw** [comment]
Sorry to reply you late. The detector can run at 12 FPS on single GTX 1080 for 640*480 resolution
image.

**Comment by EricZgw** [comment]
@tzhang2014 Sorry to reply you late. The detector can run at 13 FPS on single GTX 1080 for 640*480 resolution image.

**Comment by tzhang2014** [comment]
@EricZgw thanks ,the speed is a bit slow
