### ISSUE TITLE
Error with provided model.

### ISSUE THREAD

**Issue by huiofficial** [EricZgw/PyramidBox#19]
I downloaded the model from BaiduYun link you provided and put them into model direcotry, then I run `python3 demo.py` , and this error occured: 

> DataLossError (see above for traceback): Checksum does not match: stored 189470084 vs. calculated on the restored bytes 1055297358
>          [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
>          [[{{node save/RestoreV2/_301}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by huiofficial** [comment]
The problem is caused by the model uploaded in BaiduYun, I use model in Google Drive and everything is fine.

**Comment by destiny311** [comment]
> 
> 
> The problem is caused by the model uploaded in BaiduYun, I use model in Google Drive and everything is fine.
请问你有这个模型吗，我这儿的谷歌上的模型打不开，可以分享一波吗，我的邮件1217470741@qq.com谢谢你了

**Comment by huiofficial** [comment]
模型太大了发不了呀

destiny311 <notifications@github.com> 于2019年4月24日周三 下午2:31写道：
