### ISSUE TITLE
Change Anchor Boxes Aspect Ratio

### ISSUE THREAD

**Issue by ahkarami** [EricZgw/PyramidBox#4]
Dear @EricZgw,
Thank you for your nice work. 
If one wants to change the aspect ratios of anchor boxes for example, to 1:1.4 (width:height) the [network structure](https://github.com/EricZgw/PyramidBox/blob/03f67d8422f2f03e5ee580e2f92d4040c24bbdb4/nets/ssd.py#L37) must be changed or just the _training code_ must be changed? Would you please explain how one can change the aspect ratios of anchor boxes?

**Comment by EricZgw** [comment]
@ahkarami , sorry to reply you late. You can change the aspect ratios of anchor boxes in ssd.py line 691.
`h[0] = sizes / img_shape[0]*1.4`

**Comment by ahkarami** [comment]
@EricZgw,
Thank you for your time & response.

**Comment by destiny311** [comment]
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_4_batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[{{node batch}} = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_STRING, DT_INT64, DT_FLOAT, DT_INT64, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/padding_fifo_queue, batch/n)]]

 do you know  thie problem ?

**Comment by ahkarami** [comment]
I don't know.
