### ISSUE TITLE
AttributeError: 'module' object has no attribute 'plasma'

### ISSUE THREAD

**Issue by Adarine99** [EricZgw/PyramidBox#5]
when I run demo.py , this problem came in and I couldn't solve that，appreciate if anyone can help me.
the details as below:
def colors_subselect(colors, num_classes=21):
    dt = len(colors) // num_classes
    sub_colors = []
    for i in range(num_classes):
        color = colors[i*dt]
        if isinstance(color[0], float):
            sub_colors.append([int(c * 255) for c in color])
        else:
            sub_colors.append([c for c in color])
    return sub_colors
colors_plasma = colors_subselect(mpcm.plasma.colors, num_classes=21)
AttributeError: 'module' object has no attribute 'plasma'

**Comment by yuli1994** [comment]
need to update the version matplotlib.thanks anyway

**Comment by yuli1994** [comment]
need to update the version matplotlib.thanks anyway

**Comment by Adarine99** [comment]
need to update the version matplotlib.thanks anyway
