### ISSUE TITLE
Modification of batch_size results in ValueError

### ISSUE THREAD

**Issue by PengJiaqiao** [EricZgw/PyramidBox#9]
From 1 to 16. I got this:

```
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1592, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 520400 and 136400 for 'ssd_losses/or1' (op: 'LogicalOr') with input shapes: [520400], [136400].
```

I am not familiar with Tensorflow...

**Comment by EricZgw** [comment]
You can change the code [here](https://github.com/EricZgw/PyramidBox/blob/03f67d8422f2f03e5ee580e2f92d4040c24bbdb4/nets/ssd.py#L728). 25600->25600 * 16( your batchsize ) , 6400->6400 * 16( your batchsize )

**Comment by PengJiaqiao** [comment]
Well-done! Thanks
